version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: document_ai_postgres
    environment:
      POSTGRES_DB: documents_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - document_ai_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: document_ai_backend
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/documents_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - chroma_data:/app/chroma_db
    depends_on:
      - postgres
    networks:
      - document_ai_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: document_ai_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - document_ai_network
    command: npm start

volumes:
  postgres_data:
  uploads_data:
  chroma_data:

networks:
  document_ai_network:
    driver: bridge